#!/bin/bash
#
# Description of script

# Set colours
NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'

# Helpers
error() {
  printf "${RED}ERROR ${NC}- $*\n" >&2
}

usage() {

}


if test; then
  # do something
fi
